server:
  port: 8089
# MySql 8+ \u9A71\u52A8
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cblog?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB

# 日志的输出
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
