server:
  port: 8089
# MySql 8+ \u9A71\u52A8
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql/cblog?userUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    database: 0
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB